version: '3.5'
services:
  BMDBNOMINA:
    container_name: BMDBNOMINA
    image: postgres:12
    volumes:
      - business-manager-data:/var/lib/postgresql/data
    expose:
      - 5434
    #All services into the BM_NETWORK use the internal port 5432 external services use 5433, in config should be BMDBBNOMINA:5432
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  BMNOMINA:
    container_name: BMNOMINA
    image: business-manager-nomina-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://BMDISCOVERY:8761/eureka
        -Dspring.profiles.active=docker
        -agentlib:jdwp=transport=dt_socket,address=5002,server=y,suspend=n
    restart: on-failure:10
    expose:
      - 8002
      - 5002
    ports:
      - 8002:8002
      - 5002:5002
    depends_on:
      - BMDBNOMINA
  BMNOMINAREDIS:
    container_name: BMREDIS
    image: redis
    expose:
      - 6379
    command: [ "redis-server", "--protected-mode", "no", "--requirepass", "redis", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
      - redis-data:/data
volumes:
  business-manager-data:
  redis-data:
networks:
  default:
    external:
      name: BM_NETWORK